language: php

php:
  - '5.5'
  - '5.4'

env:
  matrix:
    - WP_VERSION=latest WP_PORT=1080 WP_PATH=/tmp/wp1
    - WP_VERSION=4.5 WP_PORT=8080 WP_PATH=/tmp/wp2

before_install:
  - curl https://raw.githubusercontent.com/vccw-team/install-wp/master/install-wp.sh | /usr/bin/env bash
  - curl https://raw.githubusercontent.com/vccw-team/install-wp/master/run-wp.sh | /usr/bin/env bash >/dev/null 2>&1 &

script:
  - ls -al $WP_PATH/wp-config.php
  - curl http://localhost:$WP_PORT/
